apiVersion: v1
kind: Service
metadata:
  name: coturn-service
  namespace: webrtc-signaling
  labels:
    app: coturn
spec:
  selector:
    app: coturn
  ports:
  - port: 3478
    targetPort: 3478
    protocol: UDP
    name: stun-udp
  - port: 3478
    targetPort: 3478
    protocol: TCP
    name: stun-tcp
  - port: 5349
    targetPort: 5349
    protocol: UDP
    name: turns-udp
  - port: 5349
    targetPort: 5349
    protocol: TCP
    name: turns-tcp
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
---
apiVersion: v1
kind: Service
metadata:
  name: coturn-service-internal
  namespace: webrtc-signaling
  labels:
    app: coturn
spec:
  selector:
    app: coturn
  ports:
  - port: 3478
    targetPort: 3478
    protocol: UDP
    name: stun-udp
  - port: 3478
    targetPort: 3478
    protocol: TCP
    name: stun-tcp
  - port: 5349
    targetPort: 5349
    protocol: UDP
    name: turns-udp
  - port: 5349
    targetPort: 5349
    protocol: TCP
    name: turns-tcp
  type: ClusterIP
