apiVersion: v1
kind: ConfigMap
metadata:
  name: signaling-config
  namespace: webrtc-signaling
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  STUN_URL: "stun:coturn-service:3478"
  TURN_URL: "turn:coturn-service:3478"
  READ_TIMEOUT: "60"
  WRITE_TIMEOUT: "60"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-config
  namespace: webrtc-signaling
data:
  turnserver.conf: |
    # STUN/TURN server configuration
    listening-port=3478
    tls-listening-port=5349
    listening-ip=0.0.0.0
    relay-ip=0.0.0.0
    realm=webrtc.local
    server-name=coturn
    lt-cred-mech
    user=webrtc:password123
    stun-only=false
    no-stun=false
    no-multicast-peers
    no-loopback-peers
    mobility
    max-port=65535
    min-port=49152
    verbose
    log-file=/var/log/coturn/turnserver.log
    pidfile=/var/run/turnserver.pid
    fingerprint
    no-cli
    no-rfc5780
    no-stun-backward-compatibility
    response-origin-only-with-rfc5780
    denied-peer-ip=10.0.0.0-10.255.255.255
    denied-peer-ip=192.168.0.0-192.168.255.255
    denied-peer-ip=172.16.0.0-172.31.255.255
    denied-peer-ip=127.0.0.0-127.255.255.255
    denied-peer-ip=169.254.0.0-169.254.255.255
